name: Package Python to EXE and Release

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 拉取所有历史记录，以便获取标签信息

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Package with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name your_program your_script.py # 确保这里是小写
        env:
          YOUR_MAIN_SCRIPT: your_script.py
          YOUR_PROGRAM_NAME: your_program

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/your_program.exe # 确保这里是小写

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: executable

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release contains the packaged executable for version ${{ github.ref_name }}.
            You can download the executable below.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: executable/your_program.exe # 确保这里是小写
          asset_name: your_program-${{ github.ref_name }}.exe # 确保这里是小写
          asset_content_type: application/vnd.microsoft.portable-executable